import SideBar from "@/components/shared/SideBar";
import { Metadata } from "next";
import React, { ReactNode } from "react";
export const metadata: Metadata = {
  title: "الحضور",
  description: "Generated by create next app",
};
const layout = ({ children }: { children: ReactNode }) => {
  return (
    <div className="flex h-screen">
      <SideBar />
      <div className="flex-1 p-8 overflow-auto">{children}</div>
    </div>
  );
};

export default layout;
