import { Metadata } from "next";
import React, { ReactNode } from "react";
export const metadata: Metadata = {
  title: "صفحة الأستاذ",
  description: "Generated by create next app",
};
const layout = ({ children }: { children: ReactNode }) => {
  return <>{children}</>;
};

export default layout;
